---

- name: "Set hostname"
  hostname:
    name="{{ inventory_hostname }}"
  when: "set_hostname | default(false)"
  tags:
    - "hostname"

- name: "Add hostname to /etc/hosts"
  lineinfile:
    dest="/etc/hosts"
    regexp="^127\.0\.0\.1"
    line="127.0.0.1 {{ inventory_hostname }} localhost"
    owner="root"
    group="root"
    mode="0644"
  when: "set_hostname | default(false)"
  tags:
    - "hostname"
